apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgdemo
  name: pgdemo
spec:
  replicas: 30
  selector:
    matchLabels:
      app: pgdemo
  template:
    metadata:
      labels:
        app: pgdemo
    spec:
      containers:
      - image: postgres:15
        name: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: examplepassword
        ports:
        - containerPort: 2345
