apiVersion: v1
kind: Service
metadata:
  labels:
    app: argodemo
  name: argodemo-svc
  namespace: argodemo
spec:
  type: nodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31111
  selector:
    app: argodemo
