---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestelportaal
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bestelportaal
  template:
    metadata:
      name: bestelportaal
      labels:
        app: bestelportaal
    spec:
      tolerations:
      - key: "size"
        operator: "Equal"
        value: "large"
        effect: "NoSchedule"
      containers:
      - name: bestelportaal
        image: httpd:2.4
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webshop
  template:
    metadata:
      name: webshop
      labels:
        app: webshop
    spec:
      containers:
      - name: webshop
        image: httpd:2.4
        ports:
        - containerPort: 80
        env:
        - name: WEBSECRET
          value: webadmin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planbord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      name: kanboard
      labels:
        app: kanboard
    spec:
      containers:
      - name: kanboard
        image: kanboard/kanboard:v1.2.20
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kanboard-web
spec:
  type: NodePort
  selector:
    app: kanboard
  ports:
    - protocol: TCP
      port: 8480
      targetPort: 80
      nodePort: 32480
